// AUTO-GENERATED by scripts/build-mock-images.cjs — do not edit by hand.
// Real product thumbnails from DummyJSON's CDN, grouped to roughly match our
// categories. Placeholder/mock imagery; replace with a real feed when available.
/* eslint-disable */

export const MOCK_IMAGES_BY_CATEGORY: Record<string, string[]> = {
  "electronics": [
    "https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/smartphones/iphone-6/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/smartphones/iphone-13-pro/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/smartphones/iphone-x/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/smartphones/oppo-a57/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/smartphones/oppo-f19-pro-plus/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/smartphones/oppo-k1/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/smartphones/realme-c35/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/smartphones/realme-x/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/smartphones/realme-xt/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s7/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s8/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/smartphones/samsung-galaxy-s10/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/smartphones/vivo-s1/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/smartphones/vivo-v9/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/smartphones/vivo-x21/thumbnail.webp"
  ],
  "fashion": [
    "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/mens-shirts/gigabyte-aorus-men-tshirt/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/mens-shirts/man-plaid-shirt/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/mens-shirts/man-short-sleeve-shirt/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/mens-shirts/men-check-shirt/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/womens-dresses/black-women's-gown/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/tops/girl-summer-dress/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/tops/gray-dress/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/tops/short-frock/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/tops/tartan-dress/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/thumbnail.webp"
  ],
  "sports": [
    "https://cdn.dummyjson.com/product-images/sports-accessories/american-football/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/sports-accessories/baseball-ball/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/sports-accessories/baseball-glove/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/sports-accessories/basketball/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/sports-accessories/basketball-rim/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/sports-accessories/cricket-ball/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/sports-accessories/cricket-bat/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/sports-accessories/cricket-helmet/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/sports-accessories/cricket-wicket/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/sports-accessories/feather-shuttlecock/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/sports-accessories/football/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/sports-accessories/golf-ball/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/sports-accessories/iron-golf/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/sports-accessories/metal-baseball-bat/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/sports-accessories/tennis-ball/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/sports-accessories/tennis-racket/thumbnail.webp"
  ],
  "beauty": [
    "https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/skin-care/attitude-super-leaves-hand-soap/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/skin-care/olay-ultra-moisture-shea-butter-body-wash/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/skin-care/vaseline-men-body-and-face-lotion/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/thumbnail.webp"
  ],
  "automotive": [
    "https://cdn.dummyjson.com/product-images/vehicle/300-touring/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/vehicle/charger-sxt-rwd/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/vehicle/dodge-hornet-gt-plus/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/vehicle/durango-sxt-rwd/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/vehicle/pacifica-touring/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/motorcycle/generic-motorcycle/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/motorcycle/kawasaki-z800/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/motorcycle/motogp-ci.h1/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/motorcycle/scooter-motorcycle/thumbnail.webp",
    "https://cdn.dummyjson.com/product-images/motorcycle/sportbike-motorcycle/thumbnail.webp"
  ]
};

export const MOCK_IMAGES_FALLBACK: string[] = [
  "https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp",
  "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp",
  "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-bed/thumbnail.webp",
  "https://cdn.dummyjson.com/product-images/groceries/apple/thumbnail.webp",
  "https://cdn.dummyjson.com/product-images/home-decoration/decoration-swing/thumbnail.webp",
  "https://cdn.dummyjson.com/product-images/kitchen-accessories/bamboo-spatula/thumbnail.webp",
  "https://cdn.dummyjson.com/product-images/laptops/apple-macbook-pro-14-inch-space-grey/thumbnail.webp",
  "https://cdn.dummyjson.com/product-images/mens-shirts/blue-&-black-check-shirt/thumbnail.webp",
  "https://cdn.dummyjson.com/product-images/mens-shoes/nike-air-jordan-1-red-and-black/thumbnail.webp",
  "https://cdn.dummyjson.com/product-images/mens-watches/brown-leather-belt-watch/thumbnail.webp",
  "https://cdn.dummyjson.com/product-images/mobile-accessories/amazon-echo-plus/thumbnail.webp",
  "https://cdn.dummyjson.com/product-images/motorcycle/generic-motorcycle/thumbnail.webp",
  "https://cdn.dummyjson.com/product-images/skin-care/attitude-super-leaves-hand-soap/thumbnail.webp",
  "https://cdn.dummyjson.com/product-images/smartphones/iphone-5s/thumbnail.webp",
  "https://cdn.dummyjson.com/product-images/sports-accessories/american-football/thumbnail.webp",
  "https://cdn.dummyjson.com/product-images/sunglasses/black-sun-glasses/thumbnail.webp",
  "https://cdn.dummyjson.com/product-images/tablets/ipad-mini-2021-starlight/thumbnail.webp",
  "https://cdn.dummyjson.com/product-images/tops/blue-frock/thumbnail.webp",
  "https://cdn.dummyjson.com/product-images/vehicle/300-touring/thumbnail.webp",
  "https://cdn.dummyjson.com/product-images/womens-bags/blue-women's-handbag/thumbnail.webp",
  "https://cdn.dummyjson.com/product-images/womens-dresses/black-women's-gown/thumbnail.webp",
  "https://cdn.dummyjson.com/product-images/womens-jewellery/green-crystal-earring/thumbnail.webp",
  "https://cdn.dummyjson.com/product-images/womens-shoes/black-&-brown-slipper/thumbnail.webp",
  "https://cdn.dummyjson.com/product-images/womens-watches/iwc-ingenieur-automatic-steel/thumbnail.webp",
  "https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp",
  "https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp",
  "https://cdn.dummyjson.com/product-images/furniture/annibale-colombo-sofa/thumbnail.webp",
  "https://cdn.dummyjson.com/product-images/groceries/beef-steak/thumbnail.webp"
];

function hash(seed: string): number {
  let h = 2166136261;
  for (let i = 0; i < seed.length; i++) { h ^= seed.charCodeAt(i); h = Math.imul(h, 16777619); }
  return h >>> 0;
}

function pool(category?: string): string[] {
  const p = category ? MOCK_IMAGES_BY_CATEGORY[category] : undefined;
  return p && p.length ? p : MOCK_IMAGES_FALLBACK;
}

/** Deterministic placeholder product image for a seed (stable per product). */
export function mockImage(seed: string, category?: string): string {
  const p = pool(category);
  return p[hash(seed) % p.length];
}

/** `n` deterministic images from the category pool (for the modal gallery). */
export function mockImages(seed: string, n: number, category?: string): string[] {
  const p = pool(category);
  const start = hash(seed) % p.length;
  return Array.from({ length: n }, (_, k) => p[(start + k) % p.length]);
}
